services:
  mongodb:
    image: mongo:7.0
    container_name: decantre-mongodb-live
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-11223345}
      MONGO_INITDB_DATABASE: perfume-store-live
    ports:
      - "27019:27017"
    volumes:
      - mongodb-data-live:/data/db
    networks:
      - decantre-live-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: decantre-backend-live
    restart: always
    env_file:
      - ./backend/.env
    environment:
      PORT: 5093
    ports:
      - "5093:5093"
    volumes:
      - /decantre/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - decantre-live-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://service.decantrebd.com
    container_name: decantre-frontend-live
    restart: always
    env_file:
      - .env
    ports:
      - "8011:8001"
    networks:
      - decantre-live-network

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://service.decantrebd.com
    container_name: decantre-dashboard-live
    restart: always
    env_file:
      - .env
    ports:
      - "8015:8005"
    networks:
      - decantre-live-network

networks:
  decantre-live-network:
    driver: bridge

volumes:
  mongodb-data-live:
    driver: local
