services:
  mongodb:
    image: mongo:7.0
    container_name: ${MONGODB_CONTAINER_NAME:-decantre-mongodb-staging}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-11223345}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-perfume-store-staging}
    ports:
      - "0.0.0.0:27018:27017"
    volumes:
      - mongodb-data-staging:/data/db
    networks:
      - decantre-stage-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${BACKEND_CONTAINER_NAME:-decantre-backend-staging}
    restart: always
    env_file:
      - .env
    environment:
      PORT: ${BACKEND_PORT:-5093}
    ports:
      - "${BACKEND_PORT:-5093}:5093"
    volumes:
      - /opt/staging/uploads:/app/uploads
      - /opt/staging/uploads:/app/src/uploads
    depends_on:
      - mongodb
    networks:
      - decantre-stage-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ${FRONTEND_CONTAINER_NAME:-decantre-frontend-staging}
    restart: always
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-8011}:8001"
    networks:
      - decantre-stage-network

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: ${DASHBOARD_CONTAINER_NAME:-decantre-dashboard-staging}
    restart: always
    env_file:
      - .env
    ports:
      - "${DASHBOARD_PORT:-8015}:8005"
    networks:
      - decantre-stage-network

networks:
  decantre-stage-network:
    driver: bridge

volumes:
  mongodb-data-staging:
    driver: local
