import { Router } from "express";
import productsRouter from "./routes/ProductsRoute.js";
import reviewRouter from "./routes/ReviewRoute.js";
import imagesRouter from "./routes/ImagesRoute.js";
import authRouter from "./routes/AuthRoute.js";
import usersRouter from "./routes/UsersRoute.js";
import assetsRouter from "./routes/AssetsRoute.js";
import membersRouter from "./routes/MembersRoute.js";
import emailRouter from "./routes/EmailRoute.js";
import ordersRouter from "./routes/OrdersRoute.js";
import paymentsRouter from "./routes/PaymentsRoute.js";
import billingRouter from "./routes/BillingRoute.js";
import categoriesRouter from "./routes/CategoryRoute.js";
import brandRouter from "./routes/BrandRoute.js";
import dashboardRouter from "./routes/DashboardRoute.js";
import couponRouter from "./routes/CouponRoute.js";
import systemRouter from "./routes/SystemRoute.js";
import searchRouter from "./routes/SearchRoute.js";
import studioRouter from "./routes/studio.js";
import logsRouter from "./routes/LogsRoute.js";
import subscriberRouter from "./routes/SubscriberRoute.js";
import contactRouter from "./routes/ContactRoute.js";
import storeUtilsRouter from "./routes/StoreUtilsRoute.js";
import reportsRouter from "./routes/ReportsRoute.js";
import express from "express";
import { searchProducts } from "./controllers/SearchController.js";

const coreRouter = Router();

coreRouter.use("/products", productsRouter);
coreRouter.use("/reviews", reviewRouter);
coreRouter.use("/images", imagesRouter);
coreRouter.use("/auth", authRouter);
coreRouter.use("/users", usersRouter);
coreRouter.use("/assets", assetsRouter);
coreRouter.use("/members", membersRouter);
coreRouter.use("/sendEmail", emailRouter);
coreRouter.use("/orders", ordersRouter);
coreRouter.use("/payments", paymentsRouter);
coreRouter.use("/billing", billingRouter);
coreRouter.use("/categories", categoriesRouter);
coreRouter.use("/brands", brandRouter);
coreRouter.use("/dashboard", dashboardRouter);
coreRouter.use("/coupons", couponRouter);
coreRouter.use("/system", systemRouter);
coreRouter.use("/subscribers", subscriberRouter);
coreRouter.use("/contact", contactRouter);
coreRouter.use("/store-utils", storeUtilsRouter);
coreRouter.use("/search", searchRouter);
coreRouter.use("/logs", logsRouter);
coreRouter.use("/reports", reportsRouter);
// Mount AI Product Image Studio routes with increased JSON payload limit for base64 image data
coreRouter.use("/studio", express.json({ limit: "60mb" }), studioRouter);
coreRouter.get("/search-products", searchProducts);

export default coreRouter;
